# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
# Recipes which backport later versions of other layers are placed here.
# Only valid for Toradex distributions.
BACKPORT_BBFILES = "${LAYERDIR}/backports/recipes-*/*/*.bb ${LAYERDIR}/backports/recipes-*/*/*.bbappend"
BBFILES += "${@ d.getVar('BACKPORT_BBFILES') if 'tdx' in d.getVar('DISTROOVERRIDES').split(':') else ''}"

BBFILE_COLLECTIONS += "toradex-st-layer"
BBFILE_PATTERN_toradex-st-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_toradex-st-layer = "22"

# Let us add layer-specific bbappends which are only applied when that
# layer is included in our configuration
BBFILES += "${@' '.join('${LAYERDIR}/%s/recipes*/*/*.bbappend' % layer \
               for layer in BBFILE_COLLECTIONS.split())}"
# Add layer-specific bb files too
BBFILES += "${@' '.join('${LAYERDIR}/%s/recipes*/*/*.bb' % layer \
               for layer in BBFILE_COLLECTIONS.split())}"

LAYERDEPENDS_toradex-st-layer = " \
    core \
    stm-st-stm32mp \
    toradex-bsp-common-layer \
"

LAYERSERIES_COMPAT_toradex-st-layer = "kirkstone"

# Torizon 6.x is based on kirkstone, add compatibility for STM32MP2 layer
LAYERSERIES_COMPAT_stm-st-stm32mp:append = " kirkstone"

# NOTE: don't apply I.MX firmware for STM32MP2 targets
BBMASK:stm32mp2common += "meta-toradex-bsp-common/recipes-kernel/linux-firmware/linux-firmware_%.bbappend"

# NOTE: disable ST images not required for TorizonOS distro
ST_BOOTFS:stm32mp2common   ?= "1"
ST_VENDORFS:stm32mp2common ?= "0"
ST_USERFS:stm32mp2common   ?= "0"

# NOTE: remove dependency on userfs since we don't build it
WKS_FILE_DEPENDS:remove:stm32mp2common = "st-image-userfs"
